/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiLeadsIndexRouteImport } from './routes/api/leads/index'
import { Route as ApiLeadsStatsRouteImport } from './routes/api/leads/stats'
import { Route as ApiLeadsSearchRouteImport } from './routes/api/leads/search'
import { Route as ApiLeadsIdRouteImport } from './routes/api/leads/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiLeadsIndexRoute = ApiLeadsIndexRouteImport.update({
  id: '/api/leads/',
  path: '/api/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsStatsRoute = ApiLeadsStatsRouteImport.update({
  id: '/api/leads/stats',
  path: '/api/leads/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsSearchRoute = ApiLeadsSearchRouteImport.update({
  id: '/api/leads/search',
  path: '/api/leads/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsIdRoute = ApiLeadsIdRouteImport.update({
  id: '/api/leads/$id',
  path: '/api/leads/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/api/leads/$id': typeof ApiLeadsIdRoute
  '/api/leads/search': typeof ApiLeadsSearchRoute
  '/api/leads/stats': typeof ApiLeadsStatsRoute
  '/api/leads/': typeof ApiLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/api/leads/$id': typeof ApiLeadsIdRoute
  '/api/leads/search': typeof ApiLeadsSearchRoute
  '/api/leads/stats': typeof ApiLeadsStatsRoute
  '/api/leads': typeof ApiLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/api/leads/$id': typeof ApiLeadsIdRoute
  '/api/leads/search': typeof ApiLeadsSearchRoute
  '/api/leads/stats': typeof ApiLeadsStatsRoute
  '/api/leads/': typeof ApiLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/leads'
    | '/api/leads/$id'
    | '/api/leads/search'
    | '/api/leads/stats'
    | '/api/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/leads'
    | '/api/leads/$id'
    | '/api/leads/search'
    | '/api/leads/stats'
    | '/api/leads'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/leads'
    | '/api/leads/$id'
    | '/api/leads/search'
    | '/api/leads/stats'
    | '/api/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiLeadsIdRoute: typeof ApiLeadsIdRoute
  ApiLeadsSearchRoute: typeof ApiLeadsSearchRoute
  ApiLeadsStatsRoute: typeof ApiLeadsStatsRoute
  ApiLeadsIndexRoute: typeof ApiLeadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/leads/': {
      id: '/api/leads/'
      path: '/api/leads'
      fullPath: '/api/leads/'
      preLoaderRoute: typeof ApiLeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads/stats': {
      id: '/api/leads/stats'
      path: '/api/leads/stats'
      fullPath: '/api/leads/stats'
      preLoaderRoute: typeof ApiLeadsStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads/search': {
      id: '/api/leads/search'
      path: '/api/leads/search'
      fullPath: '/api/leads/search'
      preLoaderRoute: typeof ApiLeadsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads/$id': {
      id: '/api/leads/$id'
      path: '/api/leads/$id'
      fullPath: '/api/leads/$id'
      preLoaderRoute: typeof ApiLeadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiLeadsIdRoute: ApiLeadsIdRoute,
  ApiLeadsSearchRoute: ApiLeadsSearchRoute,
  ApiLeadsStatsRoute: ApiLeadsStatsRoute,
  ApiLeadsIndexRoute: ApiLeadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
